---
name: Norminette

on:
  push:

jobs:
  check-norminette:
    name: Norminette
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Norminette version
        uses: iioel/norminette@v3.3.51-action
        with:
          args: '-v'

      - name: Norminette
        uses: iioel/norminette@v3.3.51-action
        with:
          args: '-RCheckForbiddenSourceHeader'